/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UserDashboardRouteImport } from './routes/_user.dashboard'
import { Route as UserPaymentsRouteImport } from './routes/_user.payments'
import { Route as UserProfileRouteImport } from './routes/_user.profile'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminPaymentChannelsRouteImport } from './routes/admin.payment-channels'
import { Route as AdminPaymentGatewayRouteImport } from './routes/admin.payment-gateway'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginVerifyRouteImport } from './routes/login.verify'
import { Route as UserInvoiceIdRouteImport } from './routes/_user.invoice.$id'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin.invoices.index'
import { Route as AdminInvoicesNewRouteImport } from './routes/admin.invoices.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserPaymentsRoute = UserPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentChannelsRoute = AdminPaymentChannelsRouteImport.update({
  id: '/payment-channels',
  path: '/payment-channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentGatewayRoute = AdminPaymentGatewayRouteImport.update({
  id: '/payment-gateway',
  path: '/payment-gateway',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UserInvoiceIdRoute = UserInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => UserRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesNewRoute = AdminInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof UserDashboardRoute
  '/payments': typeof UserPaymentsRoute
  '/profile': typeof UserProfileRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payment-channels': typeof AdminPaymentChannelsRoute
  '/admin/payment-gateway': typeof AdminPaymentGatewayRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/i/$token': typeof ITokenRoute
  '/login/verify': typeof LoginVerifyRoute
  '/login/': typeof LoginIndexRoute
  '/invoice/$id': typeof UserInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof UserDashboardRoute
  '/payments': typeof UserPaymentsRoute
  '/profile': typeof UserProfileRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payment-channels': typeof AdminPaymentChannelsRoute
  '/admin/payment-gateway': typeof AdminPaymentGatewayRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/i/$token': typeof ITokenRoute
  '/login/verify': typeof LoginVerifyRoute
  '/login': typeof LoginIndexRoute
  '/invoice/$id': typeof UserInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_user/dashboard': typeof UserDashboardRoute
  '/_user/payments': typeof UserPaymentsRoute
  '/_user/profile': typeof UserProfileRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payment-channels': typeof AdminPaymentChannelsRoute
  '/admin/payment-gateway': typeof AdminPaymentGatewayRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/i/$token': typeof ITokenRoute
  '/login/verify': typeof LoginVerifyRoute
  '/login/': typeof LoginIndexRoute
  '/_user/invoice/$id': typeof UserInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/payment-channels'
    | '/admin/payment-gateway'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/i/$token'
    | '/login/verify'
    | '/login/'
    | '/invoice/$id'
    | '/admin/invoices/new'
    | '/admin/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/payment-channels'
    | '/admin/payment-gateway'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/i/$token'
    | '/login/verify'
    | '/login'
    | '/invoice/$id'
    | '/admin/invoices/new'
    | '/admin/invoices'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/admin'
    | '/_user/dashboard'
    | '/_user/payments'
    | '/_user/profile'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/payment-channels'
    | '/admin/payment-gateway'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/i/$token'
    | '/login/verify'
    | '/login/'
    | '/_user/invoice/$id'
    | '/admin/invoices/new'
    | '/admin/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ITokenRoute: typeof ITokenRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/dashboard': {
      id: '/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/payments': {
      id: '/_user/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof UserPaymentsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-channels': {
      id: '/admin/payment-channels'
      path: '/payment-channels'
      fullPath: '/admin/payment-channels'
      preLoaderRoute: typeof AdminPaymentChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-gateway': {
      id: '/admin/payment-gateway'
      path: '/payment-gateway'
      fullPath: '/admin/payment-gateway'
      preLoaderRoute: typeof AdminPaymentGatewayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verify': {
      id: '/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/invoice/$id': {
      id: '/_user/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof UserInvoiceIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/new': {
      id: '/admin/invoices/new'
      path: '/invoices/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminInvoicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserPaymentsRoute: typeof UserPaymentsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserInvoiceIdRoute: typeof UserInvoiceIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserPaymentsRoute: UserPaymentsRoute,
  UserProfileRoute: UserProfileRoute,
  UserInvoiceIdRoute: UserInvoiceIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPaymentChannelsRoute: typeof AdminPaymentChannelsRoute
  AdminPaymentGatewayRoute: typeof AdminPaymentGatewayRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminInvoicesNewRoute: typeof AdminInvoicesNewRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPaymentChannelsRoute: AdminPaymentChannelsRoute,
  AdminPaymentGatewayRoute: AdminPaymentGatewayRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminInvoicesNewRoute: AdminInvoicesNewRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ITokenRoute: ITokenRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
